### ISSUE TITLE
Missing dependencies and configuration issues

### ISSUE THREAD

**Issue by fcisio** [teambit/getting-started#1]
Hi just followed the tutorial for this starter and I encountered some issues.

## jest-dom
`@testing-library/jest-dom` is missing from the dependencies and the docs, but is needed for the `.toBeInTheDocument()` test to run.

1. `bit install @testing-library/jest-dom/extend-expect`
2. `import "@testing-library/jest-dom/extend-expect";` wherever needed in test files (ex: button.spec.tsx)

## classnames
`classnames` is missing from the dependencies and the docs, but is needed for the `button`.

## MDX
The docs files all have the extention `.md` but really should be `.mdx`

## BVM
This note on `bit` && `bbit` should be present on bother `Installation` docs pages.
It's displayed in the main `Installation`, but not on `Tutorial / Install Bit`

> If a legacy version of Bit (Bit v14) is installed on your machine, BVM will automatically link the latest version to bbit (instead of bit) to allow you to use both versions in parallel.

**Comment by giteden** [comment]
Thanks for the feedback @fcisio 
It's all been fixed.
